from: dev-master-v10
logging:
    config: classpath:logback-spring.xml
server:
    port: 7082
spring:
    application:
        name: trace2
    sleuth:
        sampler:
            percentage: 0.5
    zipkin:
        base-url: http://127.0.0.1:9411
        rabbitmq:
            queue: zipkin
    rabbitmq:
        host: 192.168.0.164
        port: 5672
        username: admin
        password: admin
        virtual-host: /