from: dev-master-v10
logging:
    config: classpath:logback-spring.xml
server:
    port: 7082
spring:
    application:
        name: ${config.name:trace2,redis}
    sleuth:
        sampler:
            percentage: 0.5
    zipkin:
        base-url: http://127.0.0.1:9411
