from: dev-master-v10
server:
    port: 7081
spring:
    application:
        name: ${config.name:trace1,redis}
    sleuth:
        sampler:
            percentage: 0.8
    zipkin:
        base-url: http://127.0.0.1:9411
